CONFIG_STDOUT_CONSOLE=y
CONFIG_I2C=y
CONFIG_PRINTK=y
CONFIG_SENSOR=y
CONFIG_GPIO=y
CONFIG_BMI270=y

CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y


CONFIG_LOG=n